# Generated by Django 5.2.4 on 2025-07-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIlab', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
